version: '3.4'

services:
  transcluder:
    depends_on:
      - shell
      - mf1
    container_name: mftranscluder
    build: ./deployment/webserver
    ports:
      - 80:80

  shell:
    container_name: mfshell
    build:
      context: ./
      dockerfile: ./projects/mf-shell/Dockerfile
    ports:
      - 4200:4200

  mf1:
    container_name: mf1
    build:
      context: ./
      dockerfile: ./projects/mf1/Dockerfile
    ports:
      - 4300:4300
